### PR TITLE
Fixes child processes console path

### LINKED ISSUE #2: Error when launchin child processes
Hi,
I encountered an error using this package with a number of items greather than the segment size.
The child processes return the following message on each line :

===== Process Output=========
Could not open input file: bin/console

Using realpath() for the console path fixes the problem

### PR DESCRIPTION
**Pull request by pitchart**
Fixes #2

### CODE REVIEW

File: src/Parallelization.php [hunk 1]
```diff
@@ -373,7 +373,7 @@ protected function executeMasterProcess(InputInterface $input, OutputInterface $
                 ' ',
                 array_filter([
                     self::detectPhpExecutable(),
-                    'bin/console',
+                    realpath(getcwd().'/bin/console'),
```
Comment (theofidry) [inline src/Parallelization.php]: This might fail though. Could you assign it to a variable e.g. `consoleBin` and assert that the result is not false with `Assert`?

Comment (pitchart) [reply src/Parallelization.php]: Done, with fileExists()

**Comment by webmozart** [comment]
Awesome, thanks! :)
